### ISSUE TITLE
Creating a report using R Markdown

### ISSUE THREAD

**Issue by jhstern** [jhstern/Assignment-6#1]
In this assignment, I added a YAML to the R Markdown template and formatted the document as a report. I specified the title, author, and a dynamically-assigned date in the YAML for the title page. I also adjusted the layout, inserted equations, and added in-text references/a references section. 

[https://github.com/jhstern/Assignment-6/blob/main/Stern_hw_06.Rmd](url)

[https://github.com/jhstern/Assignment-6/blob/main/Stern_hw_06.pdf](url)

**Comment by mdscheuerell** [comment]
Your report looks great, Jenny!

Also, FYI, the links above don't point to the actual `.Rmd` or `.pdf` files, but I was able to copy/paste them into a new window without issue.
